# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2024-06-17T20:13:01+00:00

from __future__ import annotations
from pydantic import BaseModel, EmailStr, conint
from typing import Optional


class Person(BaseModel):
    name: str
    age: Optional[conint(ge=0)] = None
    email: EmailStr
